plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "连边"
email: 670472241@qq.com
description: "订阅号：连边"
github:
  username: lianbian
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: blog
    client_id: b4d5f3996c2b1038c398
    client_secret:  da7b579f2938ca7bc72d7c0f16dccc5e78342c57

url: "https://lianbian.github.io/"
imgrepo: "https://lianbian.github.io/static/img"
